### ISSUE TITLE
Promotion Rules Issue

### ISSUE THREAD

**Issue by aaronzdavis** [solidusio-contrib/solidus_multi_domain#104]
When adding a Store Rule to a Promotion I get this error:
```ruby
Started GET "/admin/stores.json?q=S&_=1550096220029"
Processing by Spree::Admin::StoresController#index as JSON
ActionController::UnknownFormat (Spree::Admin::StoresController#index is missing a template for this request format and variant.
```
![Store Rule Error](https://i.ibb.co/cTD6JM3/Screen-Shot-2019-02-13-at-2-31-09-PM.png)

To resolve this I created: `app/views/spree/admin/stores/index.json.jbuilder`

```ruby
json.stores(@stores) do |store|
  json.id store.id
  json.name store.name
end

json.count @stores.count
json.total_count @stores.total_count
json.current_page params[:page] ? params[:page].to_i : 1
json.per_page params[:per_page] || Kaminari.config.default_per_page
json.pages @stores.total_pages
```

But I am still unable to get results to populate in the dropdown. Even though the JSON response has stores:
`{"stores":[{"id":1,"name":"Sunday Goods"}],"count":1,"total_count":1,"current_page":1,"per_page":25,"pages":1}`

![Store Rules Empty](https://i.ibb.co/rG75Mzn/Screen-Shot-2019-02-13-at-2-36-38-PM.png)

**Comment by AlessioRocco** [comment]
@aaronzdavis can you provide some more information.

- What version of Solidus are you using? 
- Are you using the gem from git repository?
