### ISSUE TITLE
Issue while bundle install with rails 5.1.4 and solidus 2.4.1 version

### ISSUE THREAD

**Issue by chetanrana2702** [solidusio-contrib/solidus_multi_domain#77]
## bundle install issue
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (~> 5.1.4)

    solidus_multi_domain was resolved to 1.0.1, which depends on
      solidus (< 2, >= 1.0.0.pre) was resolved to 1.0.0.pre, which depends on
        solidus_core (= 1.0.0.pre) was resolved to 1.0.0.pre, which depends on
          rails (~> 4.2.0)

Bundler could not find compatible versions for gem "solidus":
  In Gemfile:
    solidus

    solidus_multi_domain was resolved to 1.0.1, which depends on
      solidus (< 2, >= 1.0.0.pre)

**Comment by photoshovel** [comment]
Hopefully you figured-out the proper way to do this already.

Here's my work-around for installing with Rails 5.1... and Solidus 2.4...:

Change to Solidus Rails application directory first.

Added following line to Solidus Gemfile:

`gem 'solidus_multi_domain', :git => 'https://github.com/solidusio/solidus_multi_domain', :branch => 'master'`

If you're using Bundler, to download the Gem:
`bundle install`

Figure-out where the Gem got stashed, which may vary on system:

`find /usr/local/rvm/ -name 'solidus_multi*'`

Then copy database migration scripts from Gem to Solidus's db/migrate directory.  Initially tried migrating without doing this and 'multi' changes did not get installed, so I did this instead:

```
cp -n  /usr/local/rvm/gems/ruby-2.4.1/bundler/gems/solidus_multi_domain-f65fafbc0f2e/db/migrate/* db/migrate/

bin/rails db:migrate RAILS_ENV=development
```

Start Rails up and you should be in business.

I also had to do some database row clean-up along the lines of:

`update spree_prices set country_iso = NULL;`

from some earlier unsuccessful hacking-around to limit products to particular stores, although that's not relevant if you weren't doing that too.
